ostro images: enable swupd, disable image variants, and re-configure images
When the "swupd" image feature gets activated (off by default for now),
the utility classes from meta-swupd are used to
a) generate swupd bundles
b) generate ostro-image-<foobar> images which consist of the core-os
   bundle plus additional, pre-installed bundles and have the swupd
   client installed.

With this in place, the CI system can build different images with swupd
support enabled. Image variants are no longer needed and more confusing
than helpful, so they get removed.

This changes images produced by our CI like this:
- ostro-image removed
- ostro-image-dev -> ostro-image-qa; this is what the CI tests run on
- new: ostro-image-reference, minimal image with ssh, getty and connectivity

Developers building locally without swupd are expected to pick which
components and features they want in their custom "ostro-image" and
directly build that. To simplify re-creating images similar in content
to those produced by the CI, some helper variables are introduced and
used by default in ostro-os-development.inc. If a developer follows
the previous instructions, they get an image that resembles
ostro-image-reference.

Documentation gets updated to reflect the changed image names
and usage model.

While cleaning up, OSTRO_EXTRA_IMAGE_FEATURES got renamed to
OSTRO_IMAGE_EXTRA_FEATURES because that is consistent with other
variables in ostro-image.bb and elsewhere (prefix derived from file).

Testing showed that the do_test_iot_export task fails when applied to
ostro-image-qa:

ERROR: ostro-image-qa-1.0-r0 do_test_iot_export: No package manifest file found: [Errno 2] No such file or directory: '....tmp-glibc/deploy/images/beaglebone/ostro-image-qa-beaglebone.manifest'

Looks like it only works for "ostro-image", so that is what is getting
used.

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>