meta-openembedded: opencv: Reorder PACKAGES variable
PACKAGES content order is important, because it determines the
destination of the files, when the folders overlaps.

Without this patch:

NOTE: Executing RunQueue Tasks
ERROR: QA Issue: non debug package contains .debug directory:
opencv-apps path
packages-split/opencv-apps/usr/share/OpenCV/java/.debug/libopencv_java310.so
[debug-files]
WARNING: QA Issue: opencv-apps: found library in wrong location:
/usr/share/OpenCV/java/libopencv_java310.so
opencv-apps: found library in wrong location:
/usr/share/OpenCV/java/.debug/libopencv_java310.so [libdir]
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa

Fixes: 3132af1d1d15 ("opencv: Fix metapkg dependencies for opencv-java ... ")

Acked-by: Otavio Salvador <otavio@ossystems.com.br>
(From meta-openembedded rev: b27938bc7ac6ab9eb2c31db15ec787c7b4a5a55d)

Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>