meta-java: rxtx: Add remove-libtool class to remove all .la files
Class remove-libtool adds a postfunc to do_install to remove all .la
files installed by libtool, so that they are absent from both the
sysroots and target packages.

Fix error:
ERROR: rxtx-2.2.0-r2 do_populate_sysroot: QA Issue: librxtxRaw.la
  failed sanity test (workdir) in path
  ../build/tmp/work/cortexa9hf-neon-emcontrols-linux-gnueabi/
  rxtx/2.2.0-r2/sysroot-destdir/usr/lib/jni [la]
ERROR: rxtx-2.2.0-r2 do_populate_sysroot: QA staging was broken by the
  package built above
ERROR: rxtx-2.2.0-r2 do_populate_sysroot: Function failed: do_qa_staging

(From meta-java rev: 33fbcd43cae1b9c08704792547159d27f2fdbe50)

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
Signed-off-by: Maxin B. John <maxin.john@intel.com>