meta-openembedded: python-backports-abc: initial recipe for version 0.4
This package backports Python 3.4 collections.abc to earlier Python versions.

It is being added as one of the two missing backport modules that Tornado 4.3
needs in order to prevent tornado/gen.py from bombing on import errors when
running on python2 rather than python3.4

  ImportError: No module named backports_abc

(From meta-openembedded rev: 4c110ff936390c9c4a908eb9cc0de8beec241eb3)

Signed-off-by: S. Lockwood-Childs <sjl@vctlabs.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>