meta-ostro: clr-systemd-config_98.bb: fix broken LIC_FILES_CHKSUM
"files://" is not the right method for finding the
license file. Correct is "file://".

"files://" no longer works with recent OE-core/bitbake, leading to:

ERROR: ExpansionError during parsing ..../clr-systemd-config_98.bb: Failure expanding variable do_fetch[file-checksums], expression was ${@bb.fetch.get_checksum_file_list(d)}  ${@get_lic_checksum_file_list(d)} which triggered exception IndexError: string index out of range

(From meta-ostro rev: 9cad874ebf0bab09fd6a7d2549a6699f00eafada)

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>