ISA_cve_plugin.py: tool output must be decoded under Python3
Under Python3, output from shell tools are byte strings.
We need to decode them (assuming utf-8 here) before they
can be used as normal strings.

This fixes this error:

  File
  "/var/lib/jenkins/ostro-worker-16-slot-1-x4trH/ostro-os/meta-security-isafw/lib/isafw/isaplugins/ISA_cve_plugin.py",
  line 193, in process_report_type
    "\ncve-check-tool terminated with exit code " + str(popen.returncode)
  TypeError: can't concat bytes to str

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>